"""Stock dossiers: stocks/TICKER.md for every ticker on the watchlist, in ledger/manual_calls.csv or in journal/trades.csv.

Usage:
  python reports/build_stocks.py              # every dossier, plus the index stocks/README.md
  python reports/build_stocks.py MTUS VYLR    # just these (the index is still rebuilt)

File contract (the deep dive above the AUTO marker is hand-written by someone else):
  # TICKER: Company name
  <!-- DEEP DIVE (hand-written; generators never touch this part) -->
  ...
  <!-- AUTO (generated by reports/build_stocks.py; everything below is rewritten on each run) -->
  ## Status                    latest price, change since first found and vs IWM, position, peers /
                               sympathy flag, next dated events
  ## Timeline                  every dated mention (scans, digests, press, triage, S1, journal,
                               calendar, research), one line per date, newest first, with links
  ## Performance since found   every ledger row for the ticker, plus its trades
A missing file is created with the heading, a "_Deep dive pending._" placeholder and both markers.
In an existing file every byte above the AUTO marker is kept as it is; only the text after the
marker is replaced (and if the marker is missing, it and the AUTO part are appended at the end).
Reads local files only (reports/sources.py); the one exception is a new file whose company name
isn't in any local file, which looks the name up once in SEC's company_tickers.json.
"""
import argparse, json, re, sys, urllib.request, datetime as dt
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from sources import (Sources, ROOT, TODAY, SECTION_ANCHOR, KIND_RANK, pct, pts, price, day, link,  # noqa: E402
                     write, word_rx, sgn, ledger_rows_for)

DEEP = "<!-- DEEP DIVE (hand-written; generators never touch this part) -->"
AUTO = "<!-- AUTO (generated by reports/build_stocks.py; everything below is rewritten on each run) -->"
SELL_COMMISSION = 0.58   # estimated commission to sell, same as collectors/positions.py
UA = {"User-Agent": "PersonalResearch research@example.com"}
_sec = None


# ---------- names ----------
def local_name(S, t):
    n = S.context.get("tickers", {}).get(t, {}).get("name")
    if n:
        return n
    idea = ROOT / f"ideas/{t}.md"
    if idea.exists():
        m = re.match(rf"# {re.escape(t)}: (.+)", idea.read_text(encoding="utf-8").splitlines()[0])
        if m:
            return m.group(1).strip()
    for d in sorted(S.market, reverse=True):
        for _, it in S.market_items(d):
            if t in it["tickers"].split("/") and it["form"] != "8-K" and it["what"]:
                return it["what"]
    return next((s["entity_raw"] for s in S.signals if s["ticker"] == t), None)


def sec_name(t):
    global _sec
    if _sec is None:
        try:
            req = urllib.request.Request("https://www.sec.gov/files/company_tickers.json", headers=UA)
            _sec = {v["ticker"]: v["title"] for v in json.load(urllib.request.urlopen(req, timeout=30)).values()}
        except Exception as e:
            print(f"  SEC name lookup failed ({e}); using the ticker as the name")
            _sec = {}
    return _sec.get(t)


KEEP_CAPS = {"LLC", "LP", "PLC", "AG", "NV", "SA", "AB", "SE", "II", "III", "US", "USA", "AI"}


def nice_name(n):
    """'RAYONIER ADVANCED MATERIALS INC.' -> 'Rayonier Advanced Materials Inc.' (mixed-case names are left alone)."""
    if not n or not n.isupper():
        return n
    return " ".join(w if w.strip(".,") in KEEP_CAPS else w.capitalize() for w in n.split())


def dossier_name(t):
    """Company name from an existing dossier's heading (whoever wrote it)."""
    p = ROOT / f"stocks/{t}.md"
    if p.exists():
        first = p.read_text(encoding="utf-8").split("\n", 1)[0]
        m = re.match(rf"#\s*{re.escape(t)}\s*[:\-–]\s*(.+)", first)
        if m:
            return m.group(1).strip()
    return None


# ---------- AUTO part ----------
def latest_price(S, t):
    """(date, close, source) from the ledger or the market context, whichever is newer."""
    cand = [(r["now_date"], r["now"], "ledger") for r in ledger_rows_for(S, t) if r["now"] is not None and r["now_date"]]
    ctx = S.context.get("tickers", {}).get(t)
    if ctx and ctx.get("last") is not None and ctx.get("as_of"):
        cand.append((dt.date.fromisoformat(ctx["as_of"]), ctx["last"], "context"))
    return max(cand, key=lambda c: (c[0], c[2] == "ledger")) if cand else None


def trade_lines(tr, mark, frm):
    side = tr.get("direction") or "LONG"
    if tr["exit_date"] and tr["exit"] is not None:
        pnl = (tr["exit"] - tr["entry"]) * tr["quantity"] * tr["sign"] - tr["fees"]
        return (f"trade #{tr['id']} ({tr['strategy']}) closed {tr['exit_date']}: {side} {tr['quantity']:g} @ ${tr['entry']:.3f} → "
                f"${tr['exit']:.3f}, P&L after fees **${pnl:+.2f}** ({tr.get('exit_reason') or 'no exit reason logged'})")
    if mark is None:
        return f"trade #{tr['id']} ({tr['strategy']}) OPEN since {tr['entry_date']}: {side} {tr['quantity']:g} @ ${tr['entry']:.3f}; no price"
    d, p, _ = mark
    pnl = (p - tr["entry"]) * tr["quantity"] * tr["sign"] - tr["fees"] - SELL_COMMISSION
    stop = f"; exit line: daily close below ${float(tr['stop']):.2f}" if tr.get("stop") else ""
    return (f"trade #{tr['id']} ({tr['strategy']}) OPEN since {tr['entry_date']}: {side} {tr['quantity']:g} @ ${tr['entry']:.3f}; "
            f"at {price(p)} ({d}) {pct((p / tr['entry'] - 1) * 100 * tr['sign'])}, P&L if sold, after all fees **${pnl:+.2f}** "
            f"(fees so far ${tr['fees']:.2f} + est. ${SELL_COMMISSION:.2f} to sell){stop}")


def status(S, t, frm):
    L = ["## Status", ""]
    rows = ledger_rows_for(S, t)
    ctx = S.context.get("tickers", {}).get(t)
    mark = latest_price(S, t)
    trades = [tr for tr in S.trades if tr["symbol"] == t]

    why = [f"open position (trade #{tr['id']})" for tr in trades if not tr["exit_date"]]
    if t in S.watchlist:
        why.append(link("watchlist", "watch/watchlist.json", frm))
    why += [f"`{m['category']}` logged {m['found']} ({m['source']})" for m in S.manual if m["ticker"] == t]
    L.append("- **Tracked because:** " + "; ".join(why))

    if mark:
        d, p, src = mark
        moves = ""
        if ctx and ctx.get("self_5d") is not None:
            moves = f" · 1d {pct(ctx.get('self_1d'))}, 5d {pct(ctx.get('self_5d'))}, 20d {pct(ctx.get('self_20d'))} (market context, {ctx['as_of']})"
        L.append(f"- **Latest price:** {price(p)} ({d}, {'ledger' if src == 'ledger' else 'market context'}){moves}")
    else:
        L.append("- **Latest price:** no price in the ledger or the market context")

    if rows:
        first = rows[0]
        how = f"found {first['found']} via `{first['category']}`" + (f" at {price(first['found_close'])}" if first["found_close"] else "")
        if first["status"] == "live":
            vs = None if first["ret_pct"] is None or first["iwm_pct"] is None else first["ret_pct"] - first["iwm_pct"]
            ex = f"; direction {sgn(first['direction'])} → excess {pct(first['excess_pct'])}" if first["excess_pct"] is not None else "; direction 0, tracked only"
            adj = re.search(r"adj: (.+)$", first.get("note") or "")
            L.append(f"- **Since first found:** **{pct(first['since_found_pct'])}** ({how}). From the next open {price(first['entry_open'])}: "
                     f"{pct(first['ret_pct'])} vs IWM {pct(first['iwm_pct'])} = **{pts(vs)}** vs IWM{ex} ({first['days']:.0f} days)"
                     + (f". Includes {adj.group(1)}" if adj else ""))
        elif first["status"].startswith("pending"):
            L.append(f"- **Since first found:** {how}; the ledger enters it at the next session's open (pending)")
        else:
            L.append(f"- **Since first found:** {how}; {first['status']}")
        if len(rows) > 1:
            L.append(f"  - {len(rows) - 1} more ledger row{'s' * (len(rows) > 2)}: see Performance since found")
    else:
        L.append("- **Since first found:** not in the ledger")

    for tr in trades:
        L.append("- **Position:** " + trade_lines(tr, mark, frm))

    if ctx:
        peer = (f"self 5d {pct(ctx.get('self_5d')) or 'n/a'} vs peer median {pct(ctx.get('peer_median_5d'))}"
                if ctx.get("peer_median_5d") is not None else "no peer median")
        flag = ctx.get("sympathy_flag") or f"no flag ({peer})"   # a flag already quotes both moves
        groups = ", ".join(f"{g} ({v['n']})" for g, v in (ctx.get("peer_groups") or {}).items())
        L.append(f"- **Peers / sympathy:** {flag}" + (f". Peer groups: {groups}" if groups else "")
                 + f" ({link('market context', 'watch/context/latest.json', frm)}, {ctx.get('as_of')})")
        for w in ctx.get("warnings") or []:
            L.append(f"  - warning: {w}")
    else:
        L.append(f"- **Peers / sympathy:** not in the market-context universe ({link('watch/context/latest.json', 'watch/context/latest.json', frm)})")

    rx = word_rx(t)
    evs = [e for e in S.events if e["date"] >= TODAY and rx.search(e["summary"] + " " + e["description"])]
    if evs:
        L.append(f"- **Next dated events** ({link('calendar', 'calendar/catalyst-dates.ics', frm)}):")
        L += [f"  - {day(e['date'])} {e['date'].year}: {e['summary']}" for e in evs[:6]]
    else:
        L.append(f"- **Next dated events:** none in the {link('calendar', 'calendar/catalyst-dates.ics', frm)}")

    files = [link("thesis", f"ideas/{t}.md", frm)] if (ROOT / f"ideas/{t}.md").exists() else []
    files += [link("ledger", "ledger/LEDGER.md", frm), link("all dossiers", "stocks/README.md", frm)]
    L.append("- **Files:** " + " · ".join(files))
    return L + [""]


def timeline(S, t, frm):
    L = ["## Timeline", "",
         "Every dated mention, newest first: S1 signals, the market-wide scan, watchlist filings, press releases, ideas and setups "
         "logged, triage notes, trades, past calendar events and research notes. One line per date; the date links to that day's scan.", ""]
    ms = S.mentions().get(t, [])
    if not ms:
        return L + ["_No dated mentions yet._", ""]
    scans = set(S.scan_dates())
    by = {}
    for m in ms:
        by.setdefault(m["date"], []).append(m)
    for d in sorted(by, reverse=True):
        items = sorted(by[d], key=lambda m: (KIND_RANK.get(m["kind"], 99), m["text"]))
        frags, seen = [], set()
        for m in items:
            if m["text"] in seen:
                continue
            seen.add(m["text"])
            lk = [link(lbl, tgt, frm) for lbl, tgt in m["links"]]
            frags.append(m["text"] + (f" ({' · '.join(lk)})" if lk else ""))
        anchor = next((SECTION_ANCHOR[m["kind"]] for m in items if m["kind"] in SECTION_ANCHOR), None)
        head = link(str(d), f"scans/{d}.md" + (f"#{anchor}" if anchor else ""), frm) if d in scans else str(d)
        L.append(f"- **{head}**: " + " · ".join(frags))
    return L + [""]


def performance(S, t, frm):
    L = ["## Performance since found", ""]
    rows = ledger_rows_for(S, t)
    if rows:
        L += [f"Every {link('ledger', 'ledger/LEDGER.md', frm)} row for {t} ({link('rules', 'ledger/RULES.md', frm)}): found = close on the day "
              "it was found; entry = next session's open; IWM over the same entry → now window; excess = direction × (return − IWM).", "",
              "| found | category | dir | 5d before | found day | $vol/day | found @ | entry @ | now | since found | since entry | IWM | excess | days | status |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
        for r in rows:
            adv = "" if r["adv_usd"] is None else (f"${r['adv_usd'] / 1e6:.1f}M" if r["adv_usd"] >= 1e6 else f"${r['adv_usd'] / 1e3:.0f}k") + ("" if r["liquid"] == "yes" else " ⚠")
            st = "live" if r["status"] == "live" else "pending" if r["status"].startswith("pending") else r["status"]
            days = "" if r["days"] is None else f"{r['days']:.0f}"
            L.append(f"| {r['found']} | `{r['category']}` | {sgn(r['direction'])} | {pct(r['pre_move_5d'])} | {pct(r['found_day_move'])} | {adv} | "
                     f"{price(r['found_close'])} | {price(r['entry_open'])} | {price(r['now'])} | {pct(r['since_found_pct'])} | {pct(r['ret_pct'])} | "
                     f"{pct(r['iwm_pct'])} | {pct(r['excess_pct'])} | {days} | {st} |")
        notes = sorted({re.sub(r"^.*\| adj: ", "adj: ", r["note"]) for r in rows if "adj:" in (r.get("note") or "")})
        if notes:
            L += [""] + [f"_Corporate-action adjustment: {n[5:]}._" for n in notes]
    else:
        L.append("_Not in the ledger yet._")
    trades = [tr for tr in S.trades if tr["symbol"] == t]
    if trades:
        mark = latest_price(S, t)
        L += ["", f"**Trades** ({link('journal', 'journal/trades.csv', frm)})", ""] + [f"- {trade_lines(tr, mark, frm)}" for tr in trades]
    return L + [""]


def auto_part(S, t):
    frm = f"stocks/{t}.md"
    L = status(S, t, frm) + timeline(S, t, frm) + performance(S, t, frm)
    while L and not L[-1]:
        L.pop()
    return "\n".join(L) + "\n"


def update(S, t):
    """Create or update stocks/TICKER.md, touching only what follows the AUTO marker. -> 'created' / 'updated' / None."""
    p = ROOT / f"stocks/{t}.md"
    auto = auto_part(S, t)
    if not p.exists():
        name = nice_name(local_name(S, t) or sec_name(t)) or t
        p.parent.mkdir(exist_ok=True)
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(f"# {t}: {name}\n{DEEP}\n_Deep dive pending._\n\n{AUTO}\n{auto}")
        return "created"
    raw = p.read_bytes().decode("utf-8")
    eol = "\r\n" if "\r\n" in raw else "\n"
    m = re.search(r"^<!-- AUTO\b[^\n]*\n?", raw, re.M)
    if m:
        head = raw[:m.end()]
        if not head.endswith("\n"):
            head += eol
    else:   # no marker yet: keep the whole file and append the marker after it
        head = raw + ("" if raw.endswith("\n") or not raw else eol) + eol + AUTO + eol
    new = head + auto.replace("\n", eol)
    if new == raw:
        return None
    with open(p, "w", encoding="utf-8", newline="") as f:
        f.write(new)
    return "updated"


def index(S):
    frm = "stocks/README.md"
    ms = S.mentions()
    scans = set(S.scan_dates())
    groups = [("Open positions", lambda t: any(tr["symbol"] == t and not tr["exit_date"] for tr in S.trades)),
              ("Watchlist", lambda t: t in S.watchlist),
              ("Ideas", lambda t: any(m["ticker"] == t and m["category"].startswith("idea_") for m in S.manual)),
              ("Setups (watch only)", lambda t: True)]
    L = ["# Stock dossiers", "",
         "One file per stock: every ticker on the watchlist (`watch/watchlist.json`), in `ledger/manual_calls.csv` or in "
         "`journal/trades.csv`. The top of each file is a hand-written deep dive; everything below the AUTO marker (status, "
         "timeline of every dated mention, performance since found) is rebuilt by `reports/build_stocks.py` every weekday morning.", ""]
    done = set()
    for title, test in groups:
        ts = [t for t in S.dossiers if t not in done and test(t)]
        if not ts:
            continue
        done |= set(ts)
        L += [f"## {title}", "", "| ticker | company | latest | since first found | vs IWM | last mention |", "|---|---|---|---|---|---|"]
        for t in ts:
            rows = ledger_rows_for(S, t)
            first = rows[0] if rows else None
            mark = latest_price(S, t)
            vs = "" if not first or first["ret_pct"] is None or first["iwm_pct"] is None else pts(first["ret_pct"] - first["iwm_pct"])
            last = max((m["date"] for m in ms.get(t, []) if m["kind"] != "calendar"), default=None)
            latest = "" if not mark else f"{price(mark[1])} ({mark[0]:%d %b})"
            since = "" if not first else f"{pct(first['since_found_pct']) or first['status'].split(' ')[0]} since {first['found']:%d %b}"
            lastm = "" if not last else link(str(last), f"scans/{last}.md", frm) if last in scans else str(last)
            L.append(f"| {link(t, f'stocks/{t}.md', frm)} | {dossier_name(t) or ''} | {latest} | {since} | {vs} | {lastm} |")
        L.append("")
    while L and not L[-1]:
        L.pop()
    return "\n".join(L) + "\n"


def write_index(generated):
    """Like update(): keep any hand-written text above the AUTO marker in stocks/README.md, regenerate below it."""
    p = ROOT / "stocks/README.md"
    if p.exists():
        raw = p.read_bytes().decode("utf-8")
        m = re.search(r"^<!-- AUTO\b[^\n]*\n?", raw, re.M)
        if m:
            head = raw[:m.end()]
            if not head.endswith("\n"):
                head += "\n"
            new = head + generated
            if new == raw:
                return False
            with open(p, "w", encoding="utf-8", newline="") as f:
                f.write(new)
            return True
    return write("stocks/README.md", generated)


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("tickers", nargs="*", help="only these tickers (default: all)")
    a = ap.parse_args()
    S = Sources()
    want = [t.upper() for t in a.tickers] or S.dossiers
    res = {}
    for t in want:
        if t not in S.dossiers:
            print(f"{t}: not on the watchlist, in manual_calls.csv or in trades.csv; skipped")
            continue
        r = update(S, t)
        if r:
            res.setdefault(r, []).append(t)
    idx = write_index(index(S))
    print(f"stocks: {len(want)} checked; " + "; ".join(f"{k} {len(v)}: {', '.join(v)}" for k, v in sorted(res.items())) +
          ("" if res else "nothing changed") + f"; index {'updated' if idx else 'unchanged'}")


if __name__ == "__main__":
    main()
